name: flutter_curve25519
description: Ed25519-like signatures with X25519 keys, Axolotl-style.
version: 0.1.0
homepage: https://github.com/randsoy/flutter_curve25519

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.0
