name: flutter_curve25519
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/randsoy/flutter_curve25519

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.0
